apiVersion: apps/v1
kind: Deployment
metadata:
  name: reply-api-deployment
  namespace: default
  labels:
    app: reply-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reply-api
  template:
    metadata:
      labels:
        app: reply-api
        version: v1
    spec:
      containers:
      - name: reply-api
        ports:
        - containerPort: 9090
        image: zaobas/reply-api:latest
      imagePullSecrets:
      - name: regcred
      
---

apiVersion: v1
kind: Service
metadata:
  name: reply-api-service
  namespace: default
  labels:
    app: reply-api
spec:
  ports:
  - name: http
    port: 9090
    targetPort: 9090
  selector:
    app: reply-api
  type: NodePort